# Generated by Django 5.2.15 on 2026-06-20 20:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique per tenant, e.g. DEP-FIN.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message="Code must be 2-30 chars, uppercase letters/digits, '-' or '_'.", regex='^[A-Z0-9][A-Z0-9_-]{1,29}$')])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent for sub-departments (DEP-03).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accesscontrol.department')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['name'],
            },
        ),
    ]
