# Generated by Django 5.2.15 on 2026-06-20 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Unique per tenant, e.g. DEP-FIN.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message="Code must be 2-30 chars: letters/digits with '-' or '_'.", regex='^[A-Za-z0-9][A-Za-z0-9_-]{1,29}$')]),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='Unique per tenant, e.g. EMP-00123.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message="Code must be 2-30 chars: letters/digits with '-' or '_'.", regex='^[A-Za-z0-9][A-Za-z0-9_-]{1,29}$')])),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accesscontrol.department')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['employee_code'],
            },
        ),
    ]
